services:
  postgres:
    image: postgres:17
    container_name: "localpostgres"
    restart: always
    networks:
      - container-link
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_data:

networks:
  container-link:
    name: "docker-localhost"
