AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  prisma-migrate-on-sam-lambda

  Sample SAM Template for prisma-migrate-on-sam-lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  PrismaMigrateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: prisma-migrate/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PrismaMigrateFunction:
    Description: "Prisma migrate Lambda Function ARN"
    Value: !GetAtt PrismaMigrateFunction.Arn
  PrismaMigrateFunctionIamRole:
    Description: "Implicit IAM Role created for Prisma migrate function"
    Value: !GetAtt PrismaMigrateFunctionRole.Arn
